version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-db
    networks:
      - app-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/product-db
      - AUTH_SERVICE_URL=http://auth-service:4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
